PnX\TaxonomieBundle\Entity\BibTaxrefHabitats:
    type: entity
    table: taxonomie.bib_taxref_habitats
    id:
        idHabitat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_habitat
            generator:
                strategy: SEQUENCE
    fields:
        nomHabitat:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nom_habitat
    lifecycleCallbacks: {  }
