PnX\TaxonomieBundle\Entity\BibTaxons:
    type: entity
    table: taxonomie.bib_taxons
    repositoryClass: PnX\TaxonomieBundle\Repository\BibTaxonsRepository
    indexes:
        i_fk_bib_taxons_taxr:
            columns:
                - cd_nom
    id:
        idTaxon:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_taxon
            generator:
                strategy: SEQUENCE
    fields:
        nomLatin:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: nom_latin
        nomFrancais:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: nom_francais
        auteur:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: auteur
        cdNom:
            type: integer
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: cd_nom
    manyToOne:
        #cdNom:
         #   targetEntity: Taxref
          #  cascade: {  }
           # mappedBy: null
            #inversedBy: null
            #joinColumns:
             #   cd_nom:
              #      referencedColumnName: cd_nom
            #orphanRemoval: false
        taxref:
            targetEntity: Taxref
            joinColumn:
                name: cd_nom
                referencedColumnName: cd_nom
    lifecycleCallbacks: {  }
