PnX\TaxonomieBundle\Entity\CorTaxonAttribut:
    type: entity
    table: taxonomie.cor_taxon_attribut
    repositoryClass: PnX\TaxonomieBundle\Repository\CorTaxonAttributRepository
    id:
      idAttribut:
        column: id_attribut
        type: integer
      idTaxon:
        column: id_taxon
        type: integer
    manyToOne:
        bib_attributs:
            targetEntity: BibAttributs
            cascade: []
            inversedBy: bib_taxons
            joinColumn:
                name: id_attribut
                referencedColumnName: id_attribut
        bib_taxons:
            targetEntity: BibTaxons
            cascade: [persist]
            inversedBy: bib_attributs
            joinColumn:
                name: id_taxon
                referencedColumnName: id_taxon
