PnX\TaxonomieBundle\Entity\CorTaxonAttribut:
    type: entity
    table: taxonomie.cor_taxon_attribut
    repositoryClass: PnX\TaxonomieBundle\Repository\CorTaxonAttributRepository
    id:
      idAttribut:
        column: id_attribut
        type: integer
      idTaxon:
        column: id_taxon
        type: integer
    fields:
        valeurAttribut:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: valeur_attribut