PnX\TaxonomieBundle\Entity\Taxref:
    type: entity
    table: taxonomie.taxref
    repositoryClass: PnX\TaxonomieBundle\Repository\TaxrefRepository
    indexes:
        i_fk_taxref_bib_taxref_habitat:
            columns:
                - id_habitat
        i_fk_taxref_bib_taxref_statuts:
            columns:
                - id_statut
        i_taxref_cd_ref:
            columns:
                - cd_ref
        i_taxref_hierarchy:
            columns:
                - regne
                - phylum
                - classe
                - ordre
                - famille
        i_fk_taxref_bib_taxref_rangs:
            columns:
                - id_rang
    id:
        cdNom:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: cd_nom
            generator:
                strategy: SEQUENCE
    fields:
        regne:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        phylum:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        classe:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        ordre:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        famille:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        cdTaxsup:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: cd_taxsup
        cdRef:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: cd_ref
        lbNom:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: lb_nom
        lbAuteur:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: lb_auteur
        nomComplet:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: nom_complet
        nomValide:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: nom_valide
        nomVern:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: nom_vern
        nomVernEng:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: nom_vern_eng
        group1Inpn:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: group1_inpn
        group2Inpn:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: group2_inpn
    manyToOne:
        idHabitat:
            targetEntity: BibTaxrefHabitats
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_habitat:
                    referencedColumnName: id_habitat
            orphanRemoval: false
        idRang:
            targetEntity: BibTaxrefRangs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rang:
                    referencedColumnName: id_rang
            orphanRemoval: false
        idStatut:
            targetEntity: BibTaxrefStatuts
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_statut:
                    referencedColumnName: id_statut
            orphanRemoval: false
    lifecycleCallbacks: {  }
