PnX\TaxonomieBundle\Entity\TaxrefProtectionEspeces:
    type: entity
    table: taxonomie.taxref_protection_especes
    indexes:
        fki_cd_nom_taxref_protection_especes:
            columns:
                - cd_nom
        IDX_7DE5A47E2830C944:
            columns:
                - cd_protection
    id:
        cdNomCite:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            id: true
            column: cd_nom_cite
    fields:
        nomCite:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: nom_cite
        synCite:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: syn_cite
        nomFrancaisCite:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: nom_francais_cite
        precisions:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    oneToOne:
        cdNom:
            targetEntity: Taxref
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cd_nom:
                    referencedColumnName: cd_nom
            orphanRemoval: false
        cdProtection:
            targetEntity: TaxrefProtectionArticles
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cd_protection:
                    referencedColumnName: cd_protection
            orphanRemoval: false
    lifecycleCallbacks: {  }
