bibfiltres:
    path:     /
    defaults: { _controller: "PnXTaxonomieBundle:BibFiltres:get" }
    methods:  [GET]
    
bibfiltres_show:
    path:     /{id}
    defaults: { _controller: "PnXTaxonomieBundle:BibFiltres:getOne" }
    methods:  [GET]

