bibtaxons:
    path:     /
    defaults: { _controller: "PnXTaxonomieBundle:BibTaxons:get" }
    methods:  [GET]	
    
bibtaxons_show:
    path:     /{id}
    defaults: { _controller: "PnXTaxonomieBundle:BibTaxons:getOne" }
    methods:  [GET]

bibtaxons_taxonomie:
    path:     /taxonomie
    defaults: { _controller: "PnXTaxonomieBundle:BibTaxons:getTaxonomie" }
    methods:  [GET]
    
bibtaxons_update:
    path:     /{id}
    defaults: { _controller: "PnXTaxonomieBundle:BibTaxons:createUpdate",id:null }
    methods:  [POST,PUT]

bibtaxons_delete:
    path:     /{id}
    defaults: { _controller: "PnXTaxonomieBundle:BibTaxons:delete" }
    methods:  [DELETE]
