taxref:
    path:     /
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:index" }
    methods:  [GET]
    
taxref_show:
    path:     /{id}
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:show" }
    methods:  [GET]

taxref_distinct_field:
    path:     distinct/{field}
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getDistinctField" }
    methods:  [GET]
    
taxref_hierarchie:
    path:     /hierarchie/{rang}
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getTaxrefHierarchie" }
    methods:  [GET]
