taxref:
    path:     /
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getTaxrefList" }
    methods:  [GET]
    
taxref_show:
    path:     /{id}
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getTaxRefDetail" }
    methods:  [GET]

taxref_distinct_field:
    path:     distinct/{field}
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getDistinctField" }
    methods:  [GET]
    
taxref_bibtaxons:
    path:     /bibtaxons/
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getTaxrefBibtaxonsList" }
    methods:  [GET]  
    
taxref_hierarchie:
    path:     /hierarchie/{rang}
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getTaxrefHierarchie" }
    methods:  [GET]

taxref_hierarchie_bibtaxons:
    path:     /hierarchiebibtaxons/{rang}
    defaults: { _controller: "PnXTaxonomieBundle:Taxref:getTaxrefHierarchieBibtaxons" }
    methods:  [GET]
    

