pn_x_taxonomie_taxref:
    resource: "@PnXTaxonomieBundle/Resources/config/routing/taxref.yml"
    prefix:   /taxref

pn_x_taxonomie_bibtaxons:
    resource: "@PnXTaxonomieBundle/Resources/config/routing/bibtaxons.yml"
    prefix:   /bibtaxons

pn_x_taxonomie_biblistes:
    resource: "@PnXTaxonomieBundle/Resources/config/routing/biblistes.yml"
    prefix:   /biblistes
    
pn_x_taxonomie_bibattributs:
    resource: "@PnXTaxonomieBundle/Resources/config/routing/bibattributs.yml"
    prefix:   /bibattributs

pn_x_index: 
    path: /
    defaults: { _controller: PnXTaxonomieBundle:Default:index }
